"""create platform tables

Revision ID: dc8b117bf393
Revises: 8465a5f72286
Create Date: 2026-08-03 10:08:13.053071

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc8b117bf393"
down_revision: str | None = "8465a5f72286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("rollout_percentage", sa.Integer(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
    )
    op.create_index(
        op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_feature_flags_tenant_id"), "feature_flags", ["tenant_id"], unique=False
    )
    op.create_table(
        "licenses",
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("user_limits", sa.Integer(), nullable=False),
        sa.Column("storage_limits", sa.Integer(), nullable=False),
        sa.Column("api_limits", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_licenses")),
    )
    op.create_index(
        op.f("ix_licenses_tenant_id"), "licenses", ["tenant_id"], unique=False
    )
    op.create_table(
        "platform_audits",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("previous_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_audits")),
    )
    op.create_index(
        op.f("ix_platform_audits_tenant_id"),
        "platform_audits",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "platform_configurations",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_configurations")),
    )
    op.create_index(
        op.f("ix_platform_configurations_key"),
        "platform_configurations",
        ["key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_configurations_tenant_id"),
        "platform_configurations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "provisioning_jobs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_step", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_jobs")),
    )
    op.create_index(
        op.f("ix_provisioning_jobs_tenant_id"),
        "provisioning_jobs",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "tenants",
        sa.Column("tenant_code", sa.String(length=50), nullable=False),
        sa.Column("tenant_name", sa.String(length=150), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("subscription_plan", sa.String(length=50), nullable=False),
        sa.Column("license_id", sa.UUID(), nullable=True),
        sa.Column("provisioning_status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(
        op.f("ix_tenants_tenant_code"), "tenants", ["tenant_code"], unique=True
    )
    op.create_table(
        "provisioning_histories",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["provisioning_jobs.id"],
            name=op.f("fk_provisioning_histories_job_id_provisioning_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_histories")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provisioning_histories")
    op.drop_index(op.f("ix_tenants_tenant_code"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(
        op.f("ix_provisioning_jobs_tenant_id"), table_name="provisioning_jobs"
    )
    op.drop_table("provisioning_jobs")
    op.drop_index(
        op.f("ix_platform_configurations_tenant_id"),
        table_name="platform_configurations",
    )
    op.drop_index(
        op.f("ix_platform_configurations_key"), table_name="platform_configurations"
    )
    op.drop_table("platform_configurations")
    op.drop_index(op.f("ix_platform_audits_tenant_id"), table_name="platform_audits")
    op.drop_table("platform_audits")
    op.drop_index(op.f("ix_licenses_tenant_id"), table_name="licenses")
    op.drop_table("licenses")
    op.drop_index(op.f("ix_feature_flags_tenant_id"), table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
